---
- name: "Wordpress Installation and configuration"
  hosts: localhost
  become: true
  vars_files:
    - apache.vars
    - mariadb.vars
    - wordpress.vars
  tasks:
    - name: "Installing Apache & PHP "
      yum:
        name:
          - httpd
          - php
          - php-gd
          - php-mysql
        state: present

    - name: "Apache - Copying Configuration"
      template:
        src: httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf

    - name: "Apache -  creating virtualhost"
      template:
        src: virtualhost.conf.j2
        dest: /etc/httpd/conf.d/{{httpd_domain}}.conf

    - name: "Apache - creating document root"
      file:
        path: /var/www/html/{{httpd_domain}}
        state: directory
        owner: "{{httpd_owner}}"
        group: "{{httpd_group}}"

    - name: "Restaring/Enabling Apache"
      service:
        name: httpd
        state: restarted
        enabled: true
    

    - name: "Mariadb - Package Installation"
      yum:
        name:
          - mariadb-server
          - MySQL-python
        state: present

    - name: "Mariadb-server - service restarting"
      service:
        name: mariadb
        state: restarted
        enabled: true

    - name: "Mariadb - updating Root password"
      ignore_errors: true
      mysql_user:
        login_user: root
        login_password: ""
        name: root
        password: "{{mysql_root}}"
        host_all: yes

    - name: "Mariadb - Removing Anonymous users"
      mysql_user:
        login_user: root
        login_password: "{{mysql_root}}"
        name: ""
        state: absent
        host_all: yes

    - name: "Mariadb- creating database"
      mysql_db:
        login_user: root
        login_password: "{{mysql_root}}"
        name: "{{mysql_database}}"

    - name: "Mariadb- Creating users"
      mysql_user:
        login_user: root
        login_password: "{{mysql_root}}"
        name: "{{mysql_user}}"
        password: "{{mysql_password}}"
        priv: "{{mysql_database}}.*:ALL"

    - name: "Wordpress URL Download"
      get_url:
        url: "{{wordpress_url}}"
        dest: /var/www/html/{{httpd_domain}}/wordpress.tar

    - name: "Extracting wordpress Archive file"
      unarchive:
        src: /var/www/html/{{httpd_domain}}/wordpress.tar
        dest: /var/www/html/{{httpd_domain}}/
        remote_src: true

    - name: "Copying Files"
      copy:
        src: /var/www/html/{{httpd_domain}}/wordpress/
        dest: /var/www/html/{{httpd_domain}}/
        remote_src: true
        owner: "{{httpd_owner}}"
        group: "{{httpd_group}}"



    - name: "Creating wp-config file"
      template:
        src: wp-config.php.j2
        dest: /var/www/html/{{httpd_domain}}/wp-config.php
        owner: "{{httpd_owner}}"
        group: "{{httpd_group}}"

    - name: "Post Installation restart"
      service:
        name: "{{item}}"
        state: restarted
        enabled: true
      with_items:
       - httpd
       - mariadb

    - name: "Post Installation- Section cleanup"
      file:
        path: "{{item}}"
        state: absent
      with_items:
        - /var/www/html/{{httpd_domain}}/wordpress.tar
        - /var/www/html/{{httpd_domain}}/wordpress
